title: "Template"
description: -- client name --, a top Real Estate Agent in -- market --, shares his/her own internal real estate agent training for free. His/Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
keywords: -- client name --, 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- market --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'

nav_USP_statement:
  # 35 characters max:
  text: What Makes You Unique Goes Here

hero:
  hero_image_path: /img/gray.png
  use_overlay: true
  overlay-intensity: 0.5
  header: Main Benefit Driven Headline Goes Here
  header_color: 'white'
  subheader: This is where you put a clear description of your primary offer and why they should click the call to action button below.
  subheader_color: 'white'
  button_text: "Call to Action Button #1"
  button_link: https://www.google.com
  open_new_tab: true

5star_reviews:
  - text: "...a few words here from a Google or Facebook review from a happy customer."
  - text: "...a few words here from a Google or Facebook review from a happy customer."
  - text: "...a few words here from a Google or Facebook review from a happy customer."
  - text: "...a few words here from a Google or Facebook review from a happy customer."


CTAS:
  - title: Call to Action 1
    url: /
  - title: Call to Action 2
    url: /
  - title: Call to Action 3
    url: /
  - title: YouTube Channel
    url: /
  - title: About us
    url: /
  - title: Reviews
    url: /

sidebar_CTAs:
  - title: Call to Action 2
    image: img/dummy-image.png
    text: Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi cum eius beatae officia magni, tenetur natus quo adipisci dolores fuga hic dicta consequatur laudantium dolor?
    button-text: CTA Button 2
    url: /
  - title: Call to Action 3
    image: img/dummy-image.png
    text: Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi cum eius beatae officia magni, tenetur natus quo adipisci dolores fuga hic dicta consequatur laudantium dolor?
    button-text: CTA Button 3
    url: /
  
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: John Doe
  title: Real Estate Agent
  license_number: 123456789
  brand: Test Brand
  brokerage: Test Brokerage
  market: Test Market
  address: 123 Main St. New York, NY 12345
  phone: 999-555-1234
  phone_type: cell
  phone2: 888-555-9876
  phone2_type: work
  email: hello@companyname54321.com
  url: www.clientwebsite.com

about:
  headline: Why Hire Us Headline 
  subheadline: Why Hire Us Subheadline
  youtube_code: NpEaa2P7qZI
  markdown: |
    Do you have this specific problem? Are you struggling to find a solution to your pain? Well, you're not alone - 57% of people in your situation feel the same way. In fact, you can expect a lot of bad things to happen to you if you don't solve this problem. You may find yourself dealing with this bad thing or that bad thing. I've heard stories even that this terrible, terrible thing has happened when the problem does not go unsolved. My name is Bob and I'm here to help you solve this problem. This is what makes my solution different from everyone else's. I have a story here where I can relate to your situation and it's why I do what I do. Here is a list of the specific things we'll do for you:
    1. Killer benefit goes here.
    2. Killer benefit goes here.
    3. Killer benefit goes here.
    4. Killer benefit goes here.
    5. Killer benefit goes here.

    The whole goal is for you to live a happier and easier life with less stress and hassle and without any worries. Those are the benefits. But don't take my word for it - we have several happy customers who have the same problem you may have who hired us to solve and can vouch for our systems. In fact, we even offer a 100% money-back guarantee to remove all the risk - you won't lose any money. I invite you to take **Call to Action #3** to learn more, **call to action #2** to really go deeper, or **Call to action #1** to get started on the solution to your problem. 

testimonials:
  - markdown_quote: |
       ### "You'll put a client testimonial here of one of your best customers that shares the problem they had before they hired you **and the benefits of you solving it."**
    name: John Doe
    image: img/16x9-placeholder.png
    image_link: https://www.google.com
  - markdown_quote: |
       ### "You'll put a client testimonial here of one of your best customers that shares the problem they had before they hired you **and the benefits of you solving it."**
    name: John Doe
    image: img/16x9-placeholder.png
    image_link: https://www.google.com
  - markdown_quote: |
       ### "You'll put a client testimonial here of one of your best customers that shares the problem they had before they hired you **and the benefits of you solving it."**
    name: John Doe
    image: img/16x9-placeholder.png
    image_link: https://www.google.com

forms:
  sitekey:

mission: This is where you put the mission or purpose of your educational video blog.

benefits_section:
  header: Main Benefit Statement Goes Here
  subheader: Repeat what makes you unique to customers here in this subheadline
  benefit_1: A top benefit of your service goes here
  benefit_2: A top benefit of your service goes here
  benefit_3: A top benefit of your service goes here
  benefit_4: A top benefit of your service goes here
  icon_image: checkmark.png
  svg_icon_color: gray

podcast:
  title: '-- market -- Real Estate Podcast with -- client name --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- client brand -- - your professional -- market -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- market --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- client name --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_dark_logo_path: /img/logo-dark.png
  hero_light_logo_path: /img/logo-light.png
  logo_width_number: 40
  hero_text: -- market -- Real Estate Video Blog
  hero_background_hex: '#999'
  post_cover: /img/cover.jpg

site_colors:
  brand_color: '#0c0c0c'
  theme_color: '#999'
  theme_text_color: 'black'
  main_body_color: 'white'
  main_body_text_color: '#212121'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#525252'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'

OG:
  image: /img/test-image.jpg
  fb-admins: test-fb-admins

footer: 
  contact_info:
    company_name: Company Name, Inc.
    address: 123 Elm Street
    city: Omaha
    state: Nebraska
    zip: 68116
    phone: 444-444-4444
    email: info@companyname.com

  socials:
    - icon: /img/icons/youtube.png
      url: https://www.youtube.com/
    - icon: /img/icons/facebook.png
      url: https://www.facebook.com/
    - icon: /img/icons/linkedin.png
      url: https://www.linkedin.com/
    - icon: /img/icons/instagram.png 
      url: https://www.instagram.com/
    - icon: /img/icons/tiktok.png
      url: https://www.tiktok.com/

  policies:
    - title: Privacy Policy
      url: /test-url
    - title: Terms of Use
      url: /test-url

bottom_mobile_cta:
  cta_1_text: Call to Action 1
  cta_1_link: https://www.google.com
  cta_2_text: Call to Action 2
  cta_2_link: https://www.google.com