title: "-- market --'s Best Real Estate Training"
description: -- client name --, a top Real Estate Agent in -- market --, shares his/her own internal real estate agent training for free. His/Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
keywords: -- client name --, 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- market --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'

nav_USP_statement:
  # 35 characters max:
  text: What Makes You Unique Goes Here

CTAS:
  - title: Call to Action 1
    url: /
  - title: Call to Action 2
    url: /
  - title: Call to Action 3
    url: /
  - title: YouTube Channel
    url: /
  - title: About us
    url: /
  - title: Reviews
    url: /

sidebar_CTAs:
  - title: Call to Action 2
    image: img/dummy-image.png
    text: Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi cum eius beatae officia magni, tenetur natus quo adipisci dolores fuga hic dicta consequatur laudantium dolor?
    button-text: CTA Button 2
    url: /
  - title: Call to Action 3
    image: img/dummy-image.png
    text: Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi cum eius beatae officia magni, tenetur natus quo adipisci dolores fuga hic dicta consequatur laudantium dolor?
    button-text: CTA Button 3
    url: /
  
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Josh Cesana
  title: Real Estate Agent
  license_number: 123456789
  about_headline: Why Hire Us Headline 
  about_subheadline: Why Hire Us Subheadline
  about_markdown: |

    This is 100 words. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in.
    
    This is 100 words. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in.

  brand: Test Brand
  brokerage: Test Brokerage
  market: Test Market
  address: 123 Main St. New York, NY 12345
  phone: 999-999-9999
  phone_type: cell
  phone2: 888-888-8888
  phone2_type: work
  email: reallylongemail@reallylongcompany.com
  url: www.testwebsite123.com

testimonials:
  - quote: Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque debitis deserunt laboriosam ut quia. Aliquam,
    name: John Doe
    image: /img/dummy-image.png
    image_link: https://www.google.com
  - quote: 				quia error pariatur molestiae, fugit voluptas eligendi sapiente quod molestias earum mollitia reprehenderit
    name: John Doe
    image: /img/dummy-image.png
    image_link: https://www.google.com
  - quote: 				laudantium nobis.
    name: John Doe
    image: /img/dummy-image.png
    image_link: https://www.google.com

forms:
  sitekey:

mission: This is where you put the mission or purpose of your educational video blog.

benefits_section:
  header: MAIN BENEFIT STATEMENT GOES HERE
  benefit_1: Benefit Statement 1 goes here with some logner text
  benefit_2: Benefit Statement 2 goes here with some logner text
  benefit_3: Benefit Statement 3 goes here with some logner text
  benefit_4: Benefit Statement 4 goes here with some logner text
  icon_image: checkmark.svg

socials:
  review_sm_icons: false
  show_socials_container: false
  facebook_url: test.com
  linkedin_url: test.com
  youtube_url: test.com
  twitter_url: test.com
  instagram_url: test.com
  pinterest_url: test.com
  zillow_url: test.com
  trulia_url: test.com
  yelp_url:
  podcast_url:
  google_business_url:

podcast:
  title: '-- market -- Real Estate Podcast with -- client name --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- client brand -- - your professional -- market -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- market --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- client name --'

hero:
  hero_image_path: /img/gray.png
  use_overlay: true
  # range from 0 - 1.0: (0.5 is default)
  overlay-intensity: 0.5
  header: Primary Call to Action Headline
  header_color: 'white'
  subheader: Primary Call to Action Subheadline
  subheader_color: 'white'
  button_text: Primary CTA Button
  button_link: https://www.google.com
  open_new_tab: true

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- market -- Real Estate Video Blog
  hero_background_hex: '#999'
  post_cover: /img/cover.jpg

site_colors:
  brand_color: 'black'
  theme_color: '#999'
  theme_text_color: 'black'
  main_body_color: 'white'
  main_body_text_color: '#212121'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#525252'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'

OG:
  image: /img/test-image.jpg
  fb-admins: test-fb-admins

policies:
  - title: Privacy Policy
    url: /test-url
  - title: Terms of Use
    url: /test-url
  - title: Accessibility Statement
    url: /test-url
  - title: DMCA Notice
    url: /test-url
